name: test_project
description: WSS Test 버전
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.1
  flutter_svg: ^1.1.3
  intl: ^0.17.0
  js: ^0.6.3
  html: ^0.15.0
  web: 0.2.1
  webview_flutter: ^3.0.4
  provider: ^6.0.0
  flutter_inappwebview: ^5.3.2
  crypto: ^3.0.1
  convert: ^3.0.0
  encrypt: ^5.0.0
  cp949_codec: ^1.0.2
  http: ^0.13.3
  googleapis: ^10.0.0
  googleapis_auth: ^1.2.0
  image_picker: ^0.8.4+1
  camera: ^0.10.0+3
  image: ^3.0.1
  pdf: ^3.6.4
  universal_html: ^2.0.9  # 웹에서 파일 다운로드를 위한 패키지






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/test_icon/
    - assets/images/
    - assets/icons/
    - assets/fonts/Roboto-Regular.ttf
